# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d45a66e8a217ed22d180ca7124a5e5e436bc72b73ce339e8456a7f92e12c17b8277ce135240f7b6a1b016587fe3c5e724482fec1251d9bcd2f3008e5a1088ba4

test:
  secret_key_base: fdde3199020ab2766e9450b420d9dd099c2d70916940d594641e463f8a2334624bcb513e039cfb5d44b847e0d9c1c0841813393a1f60d9017c36e9eaa09194c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
